annual_salary = float (input('Enter you annual salary'))
percent_of_salary = float (input ('Enter the percent of your salary to save, as a decimal'))
cost_of_dream_home = float (input(' Enter the cost of your dream home'))
print (cost_of_dream_home)
print (percent_of_salary)
print (cost_of_dream_home)